language: java
jdk:
  - oraclejdk7
  - oraclejdk8
services:
  - docker
install:
  - docker build -t container_pce .
  - docker run -d -p 4189:4189 -t --name pce container_pce:latest java -jar target/PCE-jar-with-dependencies.jar src/test/resources/PCEServerConfiguration_SSON_Line.xml

script:
  - mvn install -X -f ./pom.xml
  - mvn org.apache.maven.plugins:maven-javadoc-plugin:2.9.1:jar
  - mvn failsafe:integration-test
